### ISSUE TITLE
Server stop error

### ISSUE THREAD

**Issue by andris155** [ImagicalMine/ImagicalMine#191794] opened 2016-02-28 13:51 UTC
**DO NOT DELETE - LEAVE THIS IN YOUR ISSUE**<br>
Welcome to the ImagicalMine issue tracker!<br>
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.<br>
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.
If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!<br>
**START ISSUE DETAILS BELOW**<br>
-------------------------------
```
28.02 13:48:26 [Server] INFO Stopping other threads
28.02 13:48:29 [Server] INFO Fatal error: Uncaught TypeError: Argument 1 passed to pocketmine\level\Position::setLevel() must be an instance of pocketmine\level\Level, null given, called in phar:///ImagicalMine.phar/src/pocketmine/entity/Entity.php on line 182 and defined in phar:///ImagicalMine.phar/src/pocketmine/level/Position.php:61
28.02 13:48:29 [Server] INFO Stack trace:
28.02 13:48:29 [Server] INFO #0 phar:///ImagicalMine.phar/src/pocketmine/entity/Entity.php(182): pocketmine\level\Position->setLevel(NULL)
28.02 13:48:29 [Server] INFO #1 phar:///ImagicalMine.phar/src/pocketmine/entity/Entity.php(463): pocketmine\entity\Entity->__construct(Object(pocketmine\level\format\anvil\Chunk), Object(pocketmine\nbt\tag\CompoundTag))
28.02 13:48:29 [Server] INFO #2 phar:///ImagicalMine.phar/src/pocketmine/level/Level.php(1621): pocketmine\entity\Entity::createEntity('Item', Object(pocketmine\level\format\anvil\Chunk), Object(pocketmine\nbt\tag\CompoundTag))
28.02 13:48:29 [Server] INFO #3 p in phar:///ImagicalMine.phar/src/pocketmine/level/Position.php on line 61
28.02 13:48:29 [Multicraft] Server shut down (stopping)
```

**Comment by ecoron** [comment] 2016-02-29 20:22
maybe it's something wrong in your loaded world. Did you get this error too, with a new created one?

**Comment by andris155** [comment] 2016-03-01 09:38
I don't tested new generated world.

**Comment by CyberPowerCrazii** [comment] 2016-03-01 10:03
Caused by anvil. Try removing anvil on the map.

**Comment by keithkfng** [comment] 2016-03-01 10:05
@CyberPowerCrazii you have a good eye XD

**Comment by CyberPowerCrazii** [comment] 2016-03-01 10:07
@keithkfng yeh, btw anvil still not fixed.

**Comment by CyberPowerCrazii** [comment] 2016-03-02 03:31
close this...

**Closed** 2016-03-02 04:39 UTC
