### ISSUE TITLE
When Noteblock is on a glowstone and you touch the Noteblock,the server load will go to 100%

### ISSUE THREAD

**Issue by zzm317** [ImagicalMine/ImagicalMine#829] opened 2016-02-03 05:22 UTC
When Noteblock is on a glowstone and you touch the Noteblock,the server load will go to 100%
i don't know why=-=

**Comment by robske110** [comment] 2016-02-03 06:25
For me the server load is always on 100% because we don't have two threads...

**Comment by zzm317** [comment] 2016-02-03 06:25
@robske110 so sad

**Comment by thebigsmileXD** [comment] 2016-02-03 07:38
I know why. I won't fix it. Because your redstone is not fully done.

**Comment by Driesboy** [comment] 2016-02-03 11:23
glowstone is not redstone

**Comment by robske110** [comment] 2016-02-03 12:49
@thebigsmileXD Is the redstone in ClearSky better?

**Comment by Driesboy** [comment] 2016-02-03 13:43
yes

**Comment by thebigsmileXD** [comment] 2016-02-03 20:52
its improved.

**Comment by ecoron** [comment] 2016-02-06 08:09
I take a look in it

**Comment by ecoron** [comment] 2016-02-06 21:06
seems also it crashes by outofmemory without crashdump. saw this after activating Noteblocks.

**Comment by robske110** [comment] 2016-02-06 22:33
Just confirmed it

**Comment by ecoron** [comment] 2016-02-06 23:07
i think i'm close on it, just testing some fixes, if this works i will push...

**Closed** 2016-02-06 23:26 UTC
