### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by andris155** [ImagicalMine/ImagicalMine#231470] opened 2016-05-01 22:40 UTC
- [x] This issue isn't related to any plugins or plugin related crashes.
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.

## Reproducing the issue
randomly - player join

## Client information
PHP 7.0.2, Multicraft 2.0.1, Ubuntu 14

## Optional information
```
ImagicalMine Crash Dump Sun May 1 22:30:31 CEST 2016

Error: Call to a member function getBlockId() on null
File: /src/pocketmine/level/format/generic/BaseChunk
Line: 107
Type: notice

Code:
[98] 			return $this->sections[$y >> 4]->setBlock($x, $y & 0x0f, $z, $blockId & 0xff, $meta & 0x0f);
[99] 		}catch(ChunkException $e){
[100] 			$level = $this->getProvider();
[101] 			$this->setInternalSection($Y = $y >> 4, $level::createChunkSection($Y));
[102] 			return $this->sections[$y >> 4]->setBlock($x, $y & 0x0f, $z, $blockId & 0xff, $meta & 0x0f);
[103] 		}
[104] 	}
[105] 
[106] 	public function getBlockId($x, $y, $z){
[107] 		return $this->sections[$y >> 4]->getBlockId($x, $y & 0x0f, $z);
[108] 	}
[109] 
[110] 	public function setBlockId($x, $y, $z, $id){
[111] 		try{
[112] 			$this->sections[$y >> 4]->setBlockId($x, $y & 0x0f, $z, $id);
[113] 			$this->hasChanged = true;
[114] 		}catch(ChunkException $e){
[115] 			$level = $this->getProvider();
[116] 			$this->setInternalSection($Y = $y >> 4, $level::createChunkSection($Y));
[117] 			$this->setBlockId($x, $y, $z, $id);

Backtrace:
#0 /src/pocketmine/Player(912): pocketmine\level\Level->getSafeSpawn(pocketmine\Player Player(1))
#1 /src/pocketmine/Player(887): pocketmine\Player->doFirstSpawn(boolean)
#2 /src/pocketmine/Player(1957): pocketmine\Player->sendNextChunk(boolean)
#3 /src/pocketmine/Server(2848): pocketmine\Player->checkNetwork(boolean)
#4 /src/pocketmine/Server(2513): pocketmine\Server->tick(boolean)
#5 /src/pocketmine/Server(2369): pocketmine\Server->tickProcessor(boolean)
#6 /src/pocketmine/Server(1949): pocketmine\Server->start(boolean)
#7 /src/pocketmine/PocketMine(512): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/minecraft/multicraft/servers/server3/ImagicalMine_1.4.phar/, string /home/minecraft/multicraft/servers/server3/, string /home/minecraft/multicraft/servers/server3/plugins/)
#8 (1): require_once(string phar:///home/minecraft/multicraft/servers/server3/ImagicalMine_1.4.phar/src/pocketmine/PocketMine.php)

ImagicalMine version: 1.4 #0 [Protocol 60; API 2.0.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux server.theoldcrafters.hol.es 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64
PHP Version: 7.0.2
Zend version: 3.0.0
OS : Linux, linux

Loaded plugins:
NoAdvertisingPE 1.0.1 by Vaivez66 for API(s) 1.12.0
JoinCommands 1.4.1 by PixelGuy75 for API(s) 1.0.0
SimpleMessages 1.2 by Dutok for API(s) 1.0.0
ServerAuth 2.13 by EvolSoft for API(s) 1.11.0
MCG76_WorldEdit 0.5.2 by minecraftgenius76 for API(s) 1.8.0
ZipPluginLoader 1.1.3 by aliuly for API(s) 1.10.0
iProtector 3.1b by LDX for API(s) 1.9.0, 2.0.0
EssentialsPE 1.1.3 by LegendsOfMCPE Team for API(s) 1.12.0
PurePerms 1.3.7 by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
SurvivalGamesV3 3.0.3 by ImagicalGamer for API(s) 1.0.0, 2.0.0, 3.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtW49v28aS/lcWcvBqH0RJlGzJVuHc5TlOmgcn8dXOy91FhbEiVxJrkstySctq0f/9vpldUqRs
t2mTd8ABTWKY3B+zM7Pz45td5pdOESWqM/UPx0N/dDge+d1OLE1xnuc670x/6RSbDN2dVBdRoDrd
TqKMkUtqOpNxLAotpEhUMle5WJRpUEQ6FUtV/D3Wwe2bcP9A4D0t4xhTF/j1KoppbraS+bTf7690
ovpJlKogl4uin5QxluFHo/I7lRv3e9R/k8hlFMj4LQbf+L3DHpHomzzoZ1hJFUSkH6s7FfcXOk9k
0V+qVOVR0P+7NOpsVaa3mJIRG5aFPzYX82KMgqIGk26nyCWUMf3U2RuIXTqXsdyofP/EHx5MxbZ9
NuMFZrML+uU9h46u5EJdZXKd7jeH2fnCkfEPDrD0nv/UMsfHk51lbIf3PNSvotwUdoG51rGSKdMa
PkXLPzl6iphRafhO3Resixa10QNqV7xj+8Pjw+MnqAUrFdy+U8Va521ih08SO/JHO8Rsj/ccBtMm
cvQkkdH45DeIXOY6gHHrvEVt/BQ1/+TwKWqmkHnRojJ5qHN+JGveP3pgKhWhm5tAp6bIy6Bo2ciZ
TjJZRPNYncFZzYWWIUxGz39UQdFtUSqLKDaz2VsZpRd6uWyMAtkoXYqv5Yk1wT9A6c/MyeJyGaWm
z2o9FnCQqcjVT2WUqxudBmr/K8v15LZRNDno/PBrt6P+FbHyS4MU+LKq6kwXMjaq2wl0qIjLk2MQ
nhX0N1dFmafiWbGKDDk5s2Q+PduI58/F4Q/UZLnbf3bfFWj+mxjcDxZ4/Bk/c8s3Ny6oMVGFdEMO
vgUzJydupV8DWQSrfWby/D5QGYv+TB38glH+YFAz9IwFFKcVS9AO3PIugnnvM0l/4G8HV2wXb9JC
5amMr6wE+8/+m0hYKcAXE51Og1zJwmpqO/DAkR3+XynFH4wqrfDbIb/Z5yM888OYG7NyHkfBo7Zi
l6Y1nQ4njujvcv+ASIN/x+Bxg6UTx5I/eJQl8xhL+IlCy5dfbVeRb2zD8OH+Panhx3i0xJlRf7RL
ayXN2UqmSxXCABA3lR13+Fl26B/9ATv0x/8SO/Qnj5B9SsPfdn79C4v8hUX+wiJ/YRHGIt0OQwIZ
U5oneggtCCeYDwbnZRSHnekAuCDXhQ40Ro3xJrMIY4a9QW+AUcuowNvgM/9gQi5v42hOc3rHTKFM
JRWUnYsoLe+FFahXrJSOQ5YVbPVWOu4pI0Y9f9QbeMNDz0EZsXc48T7My7QoxdXbS/Eqj8RbuRFD
MRxNR4PpYCA+XJ+J4cA/FPfH45sxCUZV3bQzgQBDvP2M6IDXkZMHnTfaVOyggV9ifqkhkiF9vdMv
QrBaRAZbdnlOTU6S3Z5uS7eDno8WWRYrnRuKw/+U0Z36eTym/WDlfsIoHwqmBpVKeAo4pOTU7YQq
A780DX1GL4qXzYZEEnyrCc5mO5zsNBD8g/dhxuX7q+uP77+/eImmtZqbqIAchCwh8j90lMJnE8nL
1EK2mtsSHu5KeBndq/h1uZkctWQc/HkRtxRnsyYnNlp8nmBXUZLF6q3F3E3Rdjoawvm9YUuwl2Wh
b7+WTO1lEUh32fgcmdh9XoDDpjzbxuZGDeFN7X06v9PxFbhrW6L/BSLVK1d5wXHhRLm6fvH99YfL
piCdVVFkCH7r9bqnwA+R7hW35Hxvz15PxjcfdR6H5yHFnVrC3Z6mmIPeETt6Q846pCKMRKWZtF3v
+M/LmwTLCdzORonZbE0MKTA0m9W8XaLvzWda6P9E2SWTskmyIfBuT9sB/d7Oxso4KuNNe1u/wFJ3
Vt91uqd21WBbkS9W5bwX6KQvY/UjfDbXYK6RprwqS6I0QfaTBhmgvysvlBMB8xRAA7qpl0ZjUyVI
HPO2Ri5e/ldLHScc/Ydf4r8gOZttGfisUPSYXkDHe3t2ed5vCAN5zw2AbBGhNm8lm1bz75jBhVoS
1+8XRF5cK5l8tZzTZAN1QmWVf1h25tAy2G+JBg1clrm6VHnSjNXbtrbso96kLfv48NUrwIG/CSiV
QOSbdBGlUbHjFKMvN4MbuxIqhoq1xuOfUAnPdS6xpQN1nAGh5xdyuWyoY9u2awqDx0zBKvprJbB6
8a9lAFtpKLWV+V10J+PXkNT8c9TMbzs9bc8f7HpBhZVpeP5A9m4NbUdflMzbPCH9PWDydxMA4U2Z
YzxhYLechcdA5BmhOIItnb3L+k2caZj1UtBp4CyfpXtXZcqA2BfDIQHi0UCcnV9dEyIe04BEF+Hp
rBwM5OTY/oo9z/tkH4PrlXofh8K+LTz3IM8cLHfvI8QS+6T2vnt983dVSPs63vPbpH8AbVrVSuFl
Oi9O/RN/dEiN6xUk9+LIFKcDepdpqksURcgHXHnLYBWpO5UgJJhTnTIdOh/wMhslsd+nPrXmKjSF
RiLBHgdlLLnHTkjkvSNnTo/sKnGs194ijpar4lQvFluyMo0ShJ7WUomeVw1L7EuiQ2WZXegcnNZt
jhBqsDDQef2e3WVudhgtFhGYKzanQ6bGdRgivWdUUQCbm1Nq5mMXj8z8lBnYthmlwsYQOkk+fXn+
6sWHi2tqtSbr/VSqfOOWdE15QNqw/NBzL0MRDqASnv4b/4FKAGo9I++Um3gXqbUXYl8kduN03NjA
KDs9Oer5h3CxYW9k5TK8SqyXZIPVQlRY1Qm+t0liMltB+VEEbLFlztvEhiugTNEsaNmSBYzRKFGp
R8hcCVSJAhtt8CALEZDFFGKuRJQGcQnghQfxwGMstSuU1kIviMQuVSMXqis0emDiICrmuZK3YqPL
3FET0UJgn6NFxGtgi3MYYLyxpN+pdU2wH6qFxDYbsdbpN4WQWYaQJkjFCSSGgPGGTvHp6M4Kv16p
VJTZMpchCPSIpNW4JTilF7F3vQI48mI0gptYpssSNYKgE3vWntsfE+E91lgl+pn1ayef0RGWlac9
FYxUIVmlvXV0G2VAr7Kn82Wf3voXsIIbvbh5c/X+Zjw68YY3NI9VWpOaillnVaazjl3s40qRJuky
gw7iBF1s2GMObFsuUwMHhRa5m3XL/IIXPKmCtzhUd1GgxApgMeZNT5i09bntshSducOsyiLU5K62
diKOXgjzM9MvQJbCkfLjmH+HhS4K23LbE/tXdhhHtIX8MYeNhm6cHWQOKtFeUOwQFLH40MbmaHEX
SfGf5Hc8iD2wgrRTwVcrdvbVCpMl2b/REMvxavdfOmqiNLBuJBzYF6vpxeUbjEQqC63St10emJ5r
09TD3jm7fEVrjSzL1lqdvzE1Htls3TL7FCHsg6CwJuBUsFkSfr4RztJ5gos1dX9L8I8RTECnMHwZ
hiJXxvoHyU1HmZBPGuAcCvQCXjFXpGWYg/qplHwptozuMBa5tFRi3y2LjHbA5O2aiHOK0osHS6OT
wyn67ervSr5Pg+u/MJs0uJbmVtBZLh0z2REfDBRNXlSJS+NWuUY6gslivOkKruyEi9pwrK4gBUIW
gh2sIKRyakvKFF5OQxz1KzZqyIVQkOt75JhCQRUQix0yrdkjDVcsvVlQROELQUSOroiKb+h+MOd5
oaL0x56yM1vsQwqYkBha3bAknpN2yrSq+EKJK9+46PI61nOomrCNsB2w8iQqKJ4mainnmwKsiSvL
0oCZsIG/ik6Qbx0xi6x+QUnWUqp2xLCWFhHMCCEWSSxlYgvEtWpNaxIQq2TPWGpIpMk3SX+80pIZ
9Zi5qRhUwog9Ti0FgqQM/x+IQZjxd4QgKPGFQgAUZcyHC7Q1X46eEXA7QgMq3HJF6z7CGoqQSHN+
JZc1tCpfjFQs1m7pYzWEuNAaII/x4DKqckiXkTTqvBTuDEVSOHlKz1a/QIoxJysKDHaYpW6pwE23
bl/FMLvOe4o6lLx5Uu/hBNKCg/vQaaYCyvGGtURcW6XbubUoUKzKzFZkYGwrszl4gi2ngdFWA0uZ
z2EcXqDj2GJZ64qPapqtjVhys4SbBWdPZFoypmhyA9BVwkgOulUQeWAlzkxsUF4sqnCSbA2wJ97b
NM5vMJWVLuOwZiVC0FmnYsu+NWyRMfcQdTwYbKUVe6/YYR4EVrYjS6MWbpHrpIrQdrYb4TXD2c5O
QyC3oQ/N5BHr2plNZUJAt4Wm2oULdhGKq9xMfFL5RvIJW1B02adzIC5jB3kEdwjCbalZYpUROK86
GTe4fqnt5N2tpaxCMNFObdOxq7mBX1UPnOVQRsHWK01UAN8tSl0NoPC7JOkntZenDSQLY4ptyp3T
fTujKUnlAjItLNCFOHZei9ddr41rc1UnXxe59prRsOqj4JFvCqLeFZ7fcAGbZHlpr6jYQYA6GlfR
aZva7T1/SRCB46fbZDsbjY6znvgOFSXUfopCAaZ+dvmhi7ngYo44to5CQDFOBy5C1At49s5fTGos
ssUphlXUGNwTL0L44krGiz7qIAufQgV7dIthWWunOm06cwMMNKi1QNr5PbkuYTAZd21goMU/Ag3r
NcSDWSl2A4IXHy7TywqcbMsawl80aY0UwkTLLM0819AGhVw6qnm5rIxCuygsKB3lbP7qXgWlxVoU
xujerlf3GrITBlDZKutFaUTs+DV4ei58Ak0uDxLw5tUq0M2zKeA5MG7rGbsRfhMBG9FHGVyUsMv+
Mqj2jm+edqSpqvSdqk1VMFnYb7Js5cqDnTWTPtmy7FcfoYP5PMmzk6YiQeeyrucgIJ9MEftU4Rgb
M2VrDYR3qo6LBgtQUfGQIw4Uzkb23r2/Pp8KTg74F5QodFMUukyKr6fIQhyTbvWayYY1vWgZRsBf
3FRSs9FyHgU/ZKQFGepw4PIdRVibTq3V0uEE9bgcWoeedkcVXCvUf0XRgoSdS6MaS+778NBH1uqK
ITr8xzpUEfQOXMQwqsmLM5Vrok5lrjtpEgpR0q5J+MXuLh8vbM8dKBJxNUmY0MYjGa/lxlj6jlK7
foQT2FxBRwWlcSULD+zWmyqNOHLQiwK2HToVfOLGtd8aVrZS+QNT1cslV3YGZSOxX3skVnFxU7i5
2yIFHggrNiu7lSnXs3YMmVXzBIWiYpcrmP+AYQQ5hc38G1PXXIV45HB4O7L/0ZJ9y4vkzaLTLdjS
1XeU+WS6qaCQZVSmzjfIMCo+w5IQ6L+LyxLKqwuqXMw6OdxcJ7OOjcKoUVEiOXo2WzpNurapcBNc
RGiBAqflF4ku0yauMK5+qEyHDI8swJa2IE4vgFO/NV3maA2t1Vk6u6BGjAdPEGB1pMoeyMyVJThX
C8phfAJJJkHqahC2R6ONxOkfOguVdwjgtOMRnUApOjXINu7UzdluDahZqwu+7auSap0CF2XMA7VB
7PEoAkeBBSd8bpDTIRf8G4Qrvf2orRFxuSMTcvnE5VqCLLUiWjHb7hBpeLtDb+W9kLtayuzXVirc
uvbuBjkFf29dczvVbY50nHIMrqa7UGI9dGiTEJ1Le2UWSraorUkHdDVigwMdQLVRlhVkezqxlaX3
UBiX+tYy4mOsn0pVKrf7joKL79zjGWzkVBz/SYqZzsq4pujeCPY8IE4/HHw9aNUKYE/kPbY3imG2
ooBZpGQ1dbtf5wM6xCZjdwPd1tOHbWUG4L2tSKwJc86ogK6jCnoTO9stTwvYiAoBadm62bXKZB7B
a6phfMlAuckeSE2r4E1naLlEqLTtLnxbw6ps31WizX0n1/Do0LV53kltdfzeaQceitKFbtJYaTIY
Xr3XOJYHLq8ZTnW6SahiZWcz2AjT4JyKcTdAbAewBDBUKeRyCXziDsbqk0zKBvTx6e1viGdZI5rm
KdbiCGm34ub8XhIKqV4J2sH03PXfVLgH1wlroDOQqfhEjx4SbpcPRX6ok2GsK78XzXNrimP16fRS
kD4J4hAqtVXErdh30LGHAQe9hnhtz4SDLCtz3hOflWTtlKdJVhUZf0heRy/x6QiQd3Lyg1vqzF2z
ELiMsBSPrst4RoaY6TK5cDGXvtcmUOK+NuQjmG3ZJOhQPlFxwRUVnwTMy5wzBJ2+Cy61DOOlWsFL
qCipxH+fVSp8KDV7JMWUqxQMvKZpvPybHDP41Zo4ej0m6j1iTREGP9nL4IdzyBadN6+CGI1XNb09
bqku6bgAeexuiVlkIGcYRJMu+KtN2KjDuy27dSszG5VW6GaPgptLottVp+LVxYvr6fDbSffo5N7v
ju5H3eG3/rchgKmN8/v0yUxA0fj0eCCWcHBj3w6PLGKN4V43KMzn8JhOtxO5S7btrZz7rx/qvlAp
eQ5/anGG7N/4YpJyUeM1C1q95qc4KtSIP7yaeKG6o28s7Ref1ZB5AOdZNRrowicNZd5scv83pn4v
87jxuojiQjXHL4rmR53LsPmSNLtWiHr2O0y8/GjqTxbpNZnbm6nGcFRam6xoNFxdXrSERznUlL6Q
JEhz+Uyb6L757o7Q7GdJvSM0fa8W7pCnSWqV6CbjhsOhafK2gbL561X3JI7o69IhaV14dMd/NDgc
TPD47A1MaqImw8XJ+GQw9w9PjqU/BxcTOR5NgtFIHo/8YBAOF+OjI/EMtC9XvB1Dt1Shb1WK5NxU
OSD4ba4WvNMj/uRzI/lmlz+g+P5sTDsfZfb7E/thDfMZ1TR+/fV/AX9iFs0=
===END CRASH DUMP===

```

**Comment by remotevase** [comment] 2016-05-02 01:46
1) Are you using the phar or the SRC?
2) IMAGICALMINE IS NOT COMPATIBLE WITH MULTICRAFT!!!

**Comment by andris155** [comment] 2016-05-02 08:33
1. Use phar.
2. -.-

**Comment by remotevase** [comment] 2016-05-02 19:18
> 2. -.-

lol, yeah. Causes many issues like this. Try not to use it and see what happens

**Comment by andris155** [comment] 2016-05-02 19:23
My servers is very big. Uasally 100+ players online. Multicraft very useful, and very easy server management.

**Comment by remotevase** [comment] 2016-05-02 20:25
Hm, then thats unfortunate. This issue is caused by MultiCraft only, closing...

**Closed by remotevase** 2016-05-02 20:25 UTC
