### ISSUE TITLE
Stopped interface

### ISSUE THREAD

**Issue by andris155** [ImagicalMine/ImagicalMine#901] opened 2016-02-12 21:00 UTC
[17:42:16] [CRITICAL]: [Network] Stopped interface pocketmine\network\RakLibInterface due to Return value of pocketmine\Player::getDisplayName() must be of the type string, null returned

Bug in player.php: 
public function getDisplayName(): string{
return $this->displayName;
}
Fix (remove string):
public function getDisplayName(){
return $this->displayName;
}

**Comment by dterweij** [comment] 2016-02-12 21:35
Report if you use PHP7-0.13.x or PHP7-0.14.x or PHP5-0.13.x ... That is important....

**Comment by mwvent** [comment] 2016-02-12 21:37
I wonder why displayName would be null?

**Comment by ecoron** [comment] 2016-02-12 21:44
Maybe isn't the latest build?

**Comment by mwvent** [comment] 2016-02-12 21:47
I cant reproduce this on current php7-0.14 branch, instead of removing the return type perhaps we could try 

 public function getDisplayName(): string{
   return is_null($this->displayName) ? "" : $this->displayName;
  }

It would be interesting to see the backtrace if you still have it though because it appears getDisplayName is being called too early while the class is being set up - that should be the only time displayName is null. And actually @ecoron I think you are right I think I saw this a while ago in an older build and its been resolved since anyway, still would be good to check the backtrace though?

**Comment by mwvent** [comment] 2016-02-12 21:49
Oh yeah I remember now my memory is terrible https://github.com/ImagicalMine/ImagicalMine/issues/871

**Comment by ecoron** [comment] 2016-02-12 21:51
Yes there are some more issues with the nametag, which isn't displayed ahead the skin. But I think I saw the fix for this issue some commits ago...

**Comment by ecoron** [comment] 2016-02-12 21:52
:)

**Comment by mwvent** [comment] 2016-02-12 21:55
brill :-) I guess we can close this then unless @andris155 confirms this is the latest build

**Closed by mwvent** 2016-02-12 21:55 UTC
