### ISSUE TITLE
Sign-Text 'buggs' away

### ISSUE THREAD

**Issue by HimbeersaftLP** [ImagicalMine/ImagicalMine#343] opened 2015-12-21 17:16 UTC
Sometimes if you write text on a sign, and then you tap the close button, and then, there's no text on the sign. 

Sorry for my bad English, but my Main-Language is German.

**Comment by robske110** [comment] 2015-12-21 17:24
Mine too and your english is pretty good.
That bug was in pocketmine for decades...
Think of Client bug.

**Comment by HimbeersaftLP** [comment] 2015-12-21 17:27
Maybe it's a lost packet, because, if I have worse internet-connection, it works nearly never. But if the connection is better, it works nearly always.

**Comment by thebigsmileXD** [comment] 2015-12-21 18:17
I am also german ;)
Well, it is because of package loss, thats right, but also could be caused by protection plugins.

**Comment by robske110** [comment] 2015-12-21 18:28
Warum sind 20% von allen die an pocketmine arbeiten Deutsch?
🇩🇪
Won't translate that ;)

**Comment by thebigsmileXD** [comment] 2015-12-21 18:41
Meine Freundin sagt: Weil wir Deutschen es können :joy: 
Won't translate that also
But its better than once.. i remember PocketMine times where signs resetted when you use [return] many times

**Comment by HimbeersaftLP** [comment] 2015-12-21 18:58
Well, I've got WorldProtect... 
P.S.: Ich komm aus Österreich

**Comment by legoboy0215** [comment] 2015-12-23 01:16
It happens when your server is laggy and when you have color on it.

**Comment by robske110** [comment] 2015-12-23 06:16
1. My server isn't laggy (TPS: 20) (Load: 5-10%)
2. Yesterday (however) I managed to get the sign text disapiering, and i only used black text...

**Comment by thebigsmileXD** [comment] 2015-12-23 07:57
Do you have SnowHalation?
When the snow falls into the sign location the tile is removed, dunno why

**Comment by legoboy0215** [comment] 2015-12-23 08:03
No.

**Comment by robske110** [comment] 2015-12-23 10:33
Me too No

**Comment by HimbeersaftLP** [comment] 2015-12-23 13:32
No

**Comment by thebigsmileXD** [comment] 2016-01-06 12:26
Okay. Because.. sometimes that happens if something breaks the block and it comes back. Actually now it seems like MCPE and pocketmine do not support the same amount of symbols anymore.
I think they've made it like pc version, so signs actually can't have text floating over its edges

**Comment by ZombiePower** [comment] 2016-01-09 05:13
"wont fix"

**Comment by keithkfng** [comment] 2016-01-09 05:32
You never know. I still don't like it, it's annoying.

**Comment by robske110** [comment] 2016-01-09 07:35
Will fix: @thebigsmileXD pointed the problem out!

**Comment by thebigsmileXD** [comment] 2016-01-09 08:13
Actually.. You can't calculate how big the text can be with php, but making the limit less would work for now

**Comment by remotevase** [comment] 2016-01-11 02:50
The reason why this is happening: the server code allows the text to go over the single player limit. Once the amount oftentimes goes over the single player limit, minecraft automatically makes the text disappear because it is an error that does not obey the "physics rules of MCOE"

**Comment by thebigsmileXD** [comment] 2016-01-11 08:16
Not so true. The server software allows 1 symbol less. If the whole line is written, it may disappear

**Comment by remotevase** [comment] 2016-01-11 11:48
Oh... Took an educated guess up there, close enough! P

**Comment by keithkfng** [comment] 2016-01-20 10:00
I do think that this was fixed - I made a commit on here which @thebigsmileXD did on CS...

**Closed by keithkfng** 2016-01-20 10:00 UTC
Labels: Bug, Critical, Help Needed, wontfix

**Comment by thebigsmileXD** [comment] 2016-01-20 15:02
Actually, 1 letter still disappears. When you write a full line, theres the last letter gone

**Comment by keithkfng** [comment] 2016-01-20 20:52
I found that on MCPE as well... Writing a full line and some two letter words disappear at the end XD
