### ISSUE TITLE
Jenkins

### ISSUE THREAD

**Issue by GlitchPlayer** [ImagicalMine/ImagicalMine#231338] opened 2016-03-04 22:29 UTC
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.

**START ISSUE DETAILS BELOW**<br>
--------------------------------------
Look your jenkins server, build 52 have been executing due to this error
Fatal error: Cannot declare class pocketmine\tile\Dispenser, because the name is already in use in /var/lib/jenkins/jobs/ImagicalMine/workspace/src/pocketmine/tile/Dropper.php on line 13

The recent commit destroyed it.
![image](https://cloud.githubusercontent.com/assets/16515013/13542092/7b71b8e0-e29b-11e5-8a0c-68c94c7aca95.png)

**Comment by remotevase** [comment] 2016-03-05 03:34
Yes. @0-Eclipse-0 fixed this in build 53 or 54

**Comment by 0-Eclipse-0** [comment] 2016-03-05 07:10
Yep. Closing.

**Closed by 0-Eclipse-0** 2016-03-05 07:10 UTC

**Comment by remotevase** [comment] 2016-03-05 14:35
@0-Eclipse-0 reopen. All the latest builds are failing due to this error. REOPEN. Also, rename to "tile and dropper fail Jenkins builds" or something like that. Also Terminate build #57

**Comment by remotevase** [comment] 2016-03-05 14:37
Oops, meant #67

**Comment by 0-Eclipse-0** [comment] 2016-03-06 17:28
I fixed the droppers. The build error was caused by hoppers.
