### ISSUE TITLE
Tips don't send

### ISSUE THREAD

**Issue by XFuryMCPE** [ImagicalMine/ImagicalMine#231455] opened 2016-04-28 01:44 UTC
Send a tip, doesnt work. wabam.

**Comment by remotevase** [comment] 2016-04-28 02:14
It doesn't? It always seems to work for me and @Ad5001 can you give us the code that you used please?

**Comment by XFuryMCPE** [comment] 2016-04-28 02:26
$p->sendTip("Message");

**Comment by keithkfng** [comment] 2016-04-28 07:48
Sure you're allowed to use "$p"?

**Comment by Pub4Game** [comment] 2016-04-28 07:55
Bug 0.14.2

**Comment by keithkfng** [comment] 2016-04-28 08:00
@Pub4Game ???

**Comment by Pub4Game** [comment] 2016-04-28 08:08
In 0.14.2 changed Text Packet

**Comment by keithkfng** [comment] 2016-04-28 08:13
I see... Come up with a fix yet? You're pretty good with those :)

**Comment by Pub4Game** [comment] 2016-04-28 08:16
Ehh... I'll try, I have very little time. The studying takes all the time and effort

**Comment by TheDragonRing** [comment] 2016-04-28 08:20
So sendTip, sendPopup, & sendMessage no longer work? :(

**Comment by Ad5001** [comment] 2016-04-28 08:20
sendMessage should work

**Comment by Creeperface01** [comment] 2016-04-28 12:19
Popup too doesnt it?

**Comment by jerryzooyoyo** [comment] 2016-04-28 13:15
sendMessage and sendPopup works.

![478580](https://cloud.githubusercontent.com/assets/16357120/14886983/4e109946-0d86-11e6-9859-b752f7c8e33e.jpg)

**Comment by HimbeersaftLP** [comment] 2016-04-28 13:15
Pupup works too

**Comment by remotevase** [comment] 2016-04-28 19:13
we fixed this earlier today or yesterday

**Comment by XFuryMCPE** [comment] 2016-04-29 04:18
Any news...?

**Comment by keithkfng** [comment] 2016-04-29 04:24
Tried it on PM? Although @Pub4Game said it was a 0.14.2 problem...

**Comment by jerryzooyoyo** [comment] 2016-04-29 09:50
Have tried for 2 days.
The sendTip() doesn't work.
0.14.2 mobile version problem.

**Comment by XFuryMCPE** [comment] 2016-04-29 19:19
He said it was a packet change, you're the owner of this amazing projected right? Why don't you try fixing it...

**Comment by XFuryMCPE** [comment] 2016-04-29 19:19
project*

**Comment by remotevase** [comment] 2016-04-29 19:25
@XFuryMCPE because we don't know what the source of the problem is for sure, and there are other people who are much more experienced than us at determining packet changes

**Comment by ImagicalGamer** [comment] 2016-04-30 18:47
wireshark timeee. lel I have "sniffed" the packets IM sends to players it's very cool to watch

**Comment by BlackShadow1** [comment] 2016-04-30 19:56
I'll check the Text Packet.

**Comment by Creeperface01** [comment] 2016-04-30 20:00
But now you can use popup like tip
![screenshot_2016-04-30-16-41-17](https://cloud.githubusercontent.com/assets/10363500/14938290/dee79674-0f1e-11e6-9f42-b36a83737eb5.png)

**Comment by kvetinac97** [comment] 2016-04-30 20:17
MCPE developpers have deleted the sendTip function from 0.14.2 as sending popup with "\n\n" at the end makes the same thing as the Tip does.
So it can't be fixed by ImagicalMine.

**Comment by TheDragonRing** [comment] 2016-04-30 21:51
Drat. Will have to change the code in all my plugins now :'(

**Comment by remotevase** [comment] 2016-04-30 22:19
@kvetinac97 the Tip works for me...

**Comment by HimbeersaftLP** [comment] 2016-05-01 06:05
We could make it that sendTip sends a popup with \n\n at the end, so that plugins keep working in the new version.

**Comment by TheDragonRing** [comment] 2016-05-01 11:33
Good idea

**Closed** 2016-05-01 12:25 UTC

**Comment by remotevase** [comment] 2016-05-01 12:26
TheDragonRing of you hit the wrong button and open the issue, at least reclose it

**Comment by TheDragonRing** [comment] 2016-05-01 12:31
Oops sorry didn't notice was scrolling through pages quickly

**Comment by remotevase** [comment] 2016-05-01 15:53
Lol
