### ISSUE TITLE
ImagicalMine Crash Dump Fri Feb 5 02:39:18 CST 2016

### ISSUE THREAD

**Issue by ibookcc** [ImagicalMine/ImagicalMine#839] opened 2016-02-05 03:37 UTC
ImagicalMine Crash Dump Fri Feb 5 02:39:18 CST 2016

Error: Call to a member function onPlayerAction() on null
File: /src/pocketmine/Player
Line: 2559
Type: E_ERROR

Code:
[2550] 					break;
[2551] 				}
[2552] 				$this->craftingType = 0;
[2553] 				$target = $this->level->getEntity($packet->target);
[2554] 				$cancelled = false;
[2555] 				if($target instanceof Player and $this->server->getConfigBoolean("pvp", true) === false
[2556] 				){
[2557] 					$cancelled = true;
[2558] 				}
[2559] 				$target->onPlayerAction($this, $packet->action);
[2560] 				// @todo move this to the entity
[2561] 				//if($target instanceof Boat or $target instanceof Minecart){
[2562] 				if($target instanceof Boat) {
[2563] 					if($packet->action === 1){
[2564] 						$this->linkEntity($target);
[2565] 					}elseif($packet->action === 2){
[2566] 						if($this->linkedEntity == $target){
[2567] 							$target->setLinked(0, $this);
[2568] 						}
[2569] 						$target->close();

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

ImagicalMine version: 1.0dev #0 [Protocol 38; API 1.14.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux iZ28qyqou4iZ 3.10.0-123.9.3.el7.x86_64 #1 SMP Thu Nov 6 15:06:03 UTC 2014 x86_64
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
JoinAndQuit 1.0.1 by guestc for API(s) 1.12.0
EasyAuth 1.0.1 by Ibook for API(s) 1.0.0
Gift 1.0.0 by ibook for API(s) 1.0.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0
SWorld 1.1.0 by 18WYJ2 & boybook for API(s) 1.0.0
IMarry 1.0.0 by  for API(s) 1.0.0
IColor_Chat 1.5.3 by ibook for API(s) 1.0.0
FResidence 1.0.8 by FENGberd for API(s) 1.0.0
DisableFlow 1.0.0 by MUedsa for API(s) 1.8.0
IRedBag 1.0.2 by  for API(s) 1.0.0
IHelp 1.0.2 by ibook for API(s) 1.0.0
IFaction 2.0.5 by ibook for API(s) 1.0.0
IHat 1.1.2 by ibook for API(s) 1.0.0
QituShop 1.6.0 by qitu for API(s) 1.0.0
IBanCmd 1.0.0 by ibook for API(s) 1.0.0
LockUser 1.0.0 by  for API(s) 1.0.1
WorldProtect 2.0.2 by aliuly for API(s) 1.10.0
TouchIt 1.1 Alpha by Marcus, Marcus for API(s) 1.4.1
IVip 1.0.0 by ibook 修改 for API(s) 1.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNWgtz20aS/itzdOoiXZEUwbeYkusU2U685Ydiyee6DVKuITAgsQIwMAYQRaf83/frngEI0kqs
9TpX5zxM9Mx0f93Trxng904Zp6qz8MaT8dTzvMm821FFoYvO4vdOuc0x1Hn6/umbN6/fdLqdVBkj
V0S7kEkiSi2kSFW6VIWIqiwoY50JnV0mcquKc348OgZBZFWSYHkUJ7T2xBTBSa6DG1WmcaZO7HyM
J3jqLIaTyemnbidPqlWcdRaRTIzqdgIdKsKE0QF4+GX9z7JQ8uYHrMaI1xr5ZEnDFum7ch2b3uOg
kFEZZ6trqCfOxMAtHu3NlMVKlRh1axJ1q5LeY9CeZmVcbo++yyUp0HtsZx47JuM2k0BmgUoSFYIP
q+EmTVqT4uioFhZnpqQVOhLWJEJmYQ3AqOJWFYzgQmdRvPpR60TJ7Mjv5Le53+mKsqjUsTg7c7Ks
qGlL1PHvljbbs98eSuLhQM4/t+Xp5xbqPT7Yb4bbFY15JJOdeabtrTs5Ef9d6lCLVN8qQcvIocq1
EopNbFd4eyvut9aPWpZCF+KeoZdwqUAWte7T4RdNT8yOhZs+2jMVLdjXi83t1czHe7Mbf4Nb39Re
s+ct08negk8K2/YHMoa1jOmBDFaiEaNCKwhramvUC2cHC1tbaFT5ghcfDbrW32qA84NF1hGmp58p
6jgFiTbqCKsRwGUhA4Tsr51HA3F0vBC7iPf9K+fNCEWzflKl+dHSuvNx57duZ6UyVciEwh2zDGwA
eV5/EKpbyF9WcRJ2FgOkiEKXOtCYOELaknnM07xxf4Bpq7jE4+CBf7CgkDdJvKQ1/RlzqDJJqbED
21R3Iv77cP5h+0FX4/jvYtT3Bv1BzxuO+qf9UV8ls/7dfPp+OhaPPHH18lJcryvxSt+KqfAmi8F0
MRiJt9cXYjjwxsLOhIB8nYP9pD/tD/H0UWVQqzPE48AOvtemFg8CPyT80KRHQzb6m46z8yz8pSKN
f+841G1qd9+OfQ8UWZVrXRjaoFWlTBmQ5dmGv5IRhwABgsrkEqmhs6DM0O2EKgdKWoQxo6PySZuQ
SkrYnevXl76/Lz7RknS7fH11/e71mxdPQNqopYlLIKXiAIWeSrM9B6aWCg3pC/ifw3lu9uAPvh59
LdT3W+IfgP+nOGqbnx8PcQ/2ccffEjcJ9P2X9PAwewc60+n2/PJ52+I7Yhs7nKF/uo9dZ2qJ/74V
esfO95VFAJ7YgDaaB6h09U4XlBoadRxhfxu8w23w5u/+929D8Z9iqbffckesdCS7GsUDVHj+UhbF
tqWCI/y5J30jwFaW7zcyHwL4Qie6eH+xlm3vb1P3oU/6o78wCFpyocYeiAfo8uyNMnGoskC1VGkR
Dzdhvq/Js6evfkIrHH4rZXaS/5W4fhIbEvUs0ZuWFm3qF7LSy7cqNHJPifnXK9ESbLW4SKQxX1Cl
sy7LfHFystls+oEsS1Vs+0FGZe/5GxX+KFdtV3OUQ62Gf0mEWGHwrUbqQ2LkZ5Xkbcj8/OeAv3Fc
kESgdoIfgvmZ7T7bsGvSYWmY/JXInVCA34l/kM33E9LPn2Ui7y+2OKegnx+ae36Jy+pqrdtu0pD2
cU8PA/YD5n0r2LVM329Jf4i5f5TZRdquvTXl/7IHcjJh90b4A7C/wMHkLc7XLfAN6V+pu97Xwq6l
+X5L7gOAc19xiUOQCtq+vkc+jNUDn5dJXCXb/db/39gAy873NwQhtxAOi9fV9fmb67eX9+hzratg
/bytSk05iFxxnuRreVC2ZBFUVFjcj7ZK46/fG4fA93dQvli5DEoXjp/ratkPdHpyVeWqsKhOai4U
Mv8T7xUFenxIsAi/GkdK+dV0Mjr9ZpED6Qgbi+GLrkfnT1kANypzzZhP9H3sOZQtY0WH1UeXzZOw
l1aCrgD9ws8e0QH5mVqKsRiOFpP5YjwRP766pgPylMZTXYZnfjUYyFli/xo/UbJcCx0Jo6SwtML+
dfrrS2kA5Tda6S7Kcl2UZ96pNxoScbMG+F4Sm/JMRxFRZJbpCq1VL+fbq54M1rG6VanKSnOGckOc
crnJes6LsSdnFlqB9qjEWaUXyCSoEslDdkUq7xw/czabsZgEjU8vSuLVuhFt+cosTmWyLyvVy5qw
gnVTHaqzAT1FugDUhuYYrWURBrponvPb3K0O4yiKAa7cnnnMjW9USl30jCrp7tOcEdneapIDnn0M
dgSjVNgap2tgfrSO1ftQoR9zghypCMgGFgX97udo8pAEwrP/4j8wRFXqnpG3qkHIfWEv0SvyiXox
XXw090T9bZqQGwlKICJgD6oKNjg7koBZxPNUrmJsBd30wa/E9VoZJWo1hSwU3yliwwx+yFIEtPWl
WCoRZ0FShSrED/GZ/xKvK50q8rjyc55GRqorNEYKQywF30OLra4Kx0vEkcBuxVHMErBRBfwI2RGM
X6lNw+4kVJHEVhmx0dn3pZB5rmQhyGApdIVqyZYu0fmGlNXerFUmqnxVyBAM+n5GXm+ZLfxMILYK
BcsqapxFIrNVJVdK0A06W8xFCJ0tRKLBP/7INqWlF2sVOC32FwJAndpU1t/EN3Guwlj2dbE6oaeT
Fwiu9zp6//zq9fvp6LQ3fE/rYMaG0UL4yE0rv0OC3q0V2Y6ufA2ykaD3CaYs2L5lITODwILdeJit
yUgVXfNCMd7SUN3GgRJrmYUJb3IKxjZSdiL5Lhx0s67KUFOM2XcYBMZmjyky6WwQ+tVkKD38fzqd
g7KcjvB7NsTvUy+g0fEwQuZVw/A/7LqhfaI8PJ/94lezSI7HQ2/ojUenY6vkOUW/oLQDvYS7shO3
sRS/UAxhCsdSz40s+P6dFqLx2ghJLm80dHOY7cZLx0hUBi6N7A63YludXz7HTBSLkKy+G+jBfEtt
1I79U47amg+9ZaA0IuD88C+CutwK55WY7mK8Gd0Z9dG7GNumMzioDENRKGP9mGDCc28AR5qq4Kwq
4L1LRfbAFqoPleT3R6v4FnNvZVIpceREoggcg7mVh9yiKJf34BurlSoWGCXJryp+7YTgPDfbLLiW
5gbxU9wgHPs0ji4qZG+vlaRZ60Ij68PBMNt0BXcpwuVGBEAXZkhhNUMVmM2Cske0tMoQhzSFeV+x
A0IfhGqh75DHSwUTQB0OnKyBRla1cJ5T2Sr5jRniuivi8nt6gVbwqlBRhWGfPlgrjqAB9lkMySKs
Q89puWBOFPtUFIotR/5PiV7CsFTlhSXD+9KYXnDgeSWX2xKAxJWFMmDhNhHbvAGdNjEDY2MLKl6W
T21/w3aJYrgLkh7qQ8asImScWqLdfihTsdOuNPTQFMJkM8hZMcgeA1uIgc+Jh1N8icQlw//n8Klj
+hPwVJT/LfBoLnKW7xJfg8dxMwIhRfVVhTUaknkA6VIVsebKRoHIr9YCzu0OWhNsHuQgz4TkYDyj
h2BQNsy4IugM2QvhCaNRavgjm1pbotFKuFhQoNtpPpdu4oHQ24WxzUUk4TXlDyqWPL3/+WTS2TW1
sF+uAqqphm1CWK2B7dpGAZhR5Wan5mjg9DTH9wJyWo+s1itZLLH5vUAniW3+KLzutSr7EkFxa4Rb
g8BNZVZx9W6jQGNTwRGOu3VCOPAE5wo2qUZRnRjSnYv1xWtbOvkJ7rDWVRI2QGKkj00mdtDJaUXO
yKHgdDCwOopHzzgMPkuM7Ct2daNUVOi0zq+01o332imptadQwm3doSvc4z+tddRAB+squzHW3i/Y
5SkbMpGQ0eGEtBG20e5ybBboZYyd1KN2gtqiHS9iVW+zi5LR1OF8ou2yw+2znzLUy9ocrBQ37Rvo
zFUIhwn4rtW6bo2dIBpoSvefsvKzTJW0F00XCNdIbBlcyhInHOpC+OUyqh/8yaUkDkDb47pRm4mW
qimInGsetXNXPUKBX2xL4t0VPa/lzFT4WGyvrKEgrUymNqvsCi2fMqjKhTbXuQ20a0F0mPriZ5yi
YN4ztNVw3IvLt12sBYIl8s8mDnE65JTN8d2w7zH7hfBcV7DrFwwbpjW1L85DxNNaJtEJzgu2hQkV
/MwJgkjrfzprB2RTmlu8Ws3WHcUetUAy6dq4Jrnv4gz9KLSC1yj2bKrzby+zy7pL2HX/1ADRog3y
vE+tf5b33GO7H8OpSi2r1cI1HI+FR42GqyrUUfJw3U0aTmNrVXeZvtsJZyrbIxpxYkpZVvCXk1Vg
LYu0FpqW0PrQuHcCUXUDSbihiT178VTnXaQu73cAG5bsYG5Jzy5ZiBRDK3cygUJ8n0Fw4XHwUc5J
co8/Eied7cqWePdNyQEaDlHeuUevXl8/XQhOuvg3qHBMy3BMY0ZxmifcvTI8J7mB17TB53u7FeBE
gkTidGUn4ooEJOQ0JTnOcOAqCGUyW5jIi+iQTHRXjZwL7ZPrFGb74CuKVlJwKY1qCTvyECf3SOmK
IQa8+wZUGfSPOWaNaqNgd7gmznRIc/cbQiEvWXlU+e1O8nF4d06mPMAnIOqcKBvIZCO3xvJ2fFpW
dKcSxIZLIGi/JXOEwVgcp8rdicQN7xLgXgFgRzxPdZW1K4hxHV+tBhmA8NCBA8mdfi7E+I+XygLU
0MKxPPbLFncQ9yxm98yUPdIulWW2VBFlMr78oYxH+9gwtVdCrdRpM+eVvEXRpuYwppO7orNbvnW3
FK6WNQ0RZ5qIL8fqtOrSYFQlPE0b+HqPYjwOrH35/FbQ1QA8C2xrS/1D0zHKBpeRKTlbyrmWClSj
fpMV7F6QPeu9eCnvhDy0Cw5QAdeXnUPtbwWb840M48q0lrltkA4dR7ld6hyX5mMzKKnR3VuvykM4
c8vdgkRJK4TvBXdOVJffZaKDnQLi1wmy6ez0N9cT81UUJbAYqHlq04hxBrJgaksj3RgKhMuL7223
vKuSgu4wUpWUXEC5iVtWBbsD3VcIrqyGg3Nn1t2ZtbZs/3PTuvS+kTFfP3yoVKWc97n1nNWY3jNw
pYWYfxW3XOdV4ri531R4Dxj7GaecHvaWQNv7zx57ObbFo31OUYlKupqqiS750b3hQkypca3djT4W
q/KFOOVm1sYKJ0bbQzlO4DGjRU4asZzQ40aSmIbINJkuYwSlneIuLO3dw8ImWromoe/VhKXa9sH5
rw0sd0hpEjeFXI+uwfYpTanco+brPM4ivfPQtSa3ZJH91qUoejzGl+lsm9IJhoPXwLimAUpO5obF
bpgBIwykkKsVKqu79Giuk6j9pa/2bu7XxuIhduY+PEmMumEhPL2TVDjtA3Ue8Bz3YmMh3A8ewr7S
cRfRRT97qBZdPv/+RhxtNqr7ifYFLPcPdd9vD1/1BTefqu67z+Ww43JkuPSTE6foCGIAdbW6BZ2l
MgD+JehKnJIRV4adtIV49uL8ejH8YdadnN553dHdqDv8wfshREm18XlUFgoPiKWz+UCssJnGPo0n
x3zdHbv7692Ft/viWd2VKiNL8Ud+FygUrY8FKZm1HpGvV83CPKCp7sF8SOJSjexnjT37BeVH+53j
kF8vLQN0Luvdd9Yygf/IYkewX4HXT1WxQxjFSUmvTcHas19VRWXejK7S3e81fNi+0sKkfxj3fmvI
H/KlS3vv20xG17fNy50GpSRAYUvdq8sXLJV+5wG6td3aLRTm7yjdLzGhN7MeaS569HppOJgMRvj5
3XNsaDSajZSchOFkMprPpt54MJXzwXAox8u5HM3GY2++HI4HSnwHSZdrMkvzFjXXJr7bGd2dxt0E
jxR9oyJ3lASV5c3VJAoketExxA6i2SyYzefTyQSiR6fDkRoNlqez0zBkeWad6p0JDUec2dc0tsbH
5FLfqAyptmgo75S8KVRkDcXfaGwlv0+hTx9owkd6/2i/9aSvUa90VQTqp4oOFZI3CHyw7tOnfwJY
vEjM
===END CRASH DUMP===
on #608

**Comment by robske110** [comment] 2016-02-05 06:16
Duplicate! But @ImagicalCorporation do you notice how big this bug is??

**Comment by GreenNature-MC-Server** [comment] 2016-02-05 10:56
This bug is why my server crashs every 30 minutes... (Crash Log Spam in my home directory)

**Comment by applqpak** [comment] 2016-02-05 11:05
Can you tell me what you do up until this crash....?

**Comment by keithkfng** [comment] 2016-02-05 11:08
@applqpak Nothing.

**Comment by applqpak** [comment] 2016-02-05 11:24
Ok

**Comment by astersx** [comment] 2016-02-05 13:30
Told ya 😃!!!!

**Comment by rWardy** [comment] 2016-02-05 13:50
I'm not getting this on my server with very latest build, so there must be something different happening.  I've not used any Minecarts, but have been using Boats.  Can anybody shed any light on specifics around the crash.  Somebody mentioned killing a mob, but I've done that as well.

**Comment by FienixEC** [comment] 2016-02-05 13:54
i had 26 players online last night, as i can not track each players
actions, i was unable to identify the exact cause, but my server would
crash every 5 minutes with this same crash dump report. sorry not much help
but, i want to stress it is an issue needing major attention.

**Comment by robske110** [comment] 2016-02-05 14:28
Its caused by minecarts! I've banned them afterwards and the crashes got less but they were still there
Switched most servers to clearsky now...

**Comment by Driesboy** [comment] 2016-02-05 15:14
remove mine carts and boats

**Comment by iMelsom** [comment] 2016-02-05 16:55
I'm not so sure about minecarts being the (only) culprit. My server do not have minecarts, but still crash. Same chrasdump as the reported dump.  It might be that it comes with using spawn eggs, since the kids using my server have discovered them. 

Here is the server.log from the last run up to the crash from the server: 

2016-02-04 [10:59:24] system> -------------------------------------------------------------------------------------------
2016-02-04 [10:59:24] system> | _ _ _ __ __ _ |
2016-02-04 [10:59:24] system> | (_) (_) | | \/ (_) |
2016-02-04 [10:59:24] system> | _ _ __ ___ __ _ __ _ _ ___ __ _| | \ / |_ _ __ ___ |
2016-02-04 [10:59:24] system> | | | '_ ` _ \ / _` |/ _` | |/ __/ _` | | |\/| | | '_ \ / _ \ ImagicalMine 1.0dev |
2016-02-04 [10:59:24] system> | | | | | | | | (_| | (_| | | (_| (_| | | | | | | | | | __/ |
2016-02-04 [10:59:24] system> | |_|_| |_| |_|\__,_|\__, |_|\___\__,_|_|_| |_|_|_| |_|\___| for MCPE v0.13.2 alpha |
2016-02-04 [10:59:24] system> | __/ | |
2016-02-04 [10:59:24] system> | |___/ |
2016-02-04 [10:59:24] system> ------------------------------------------------------------------------------------------- 
2016-02-04 [10:59:24] system> 
2016-02-04 [10:59:24] system> ImagicalMine is a third-party build of PocketMine-MP, distributed under the LGPL licence
2016-02-04 [10:59:24] system> Loading ImagicalMine system files....
2016-02-04 [10:59:24] system> Loading server properties...
2016-02-04 [10:59:24] system> Enabled log writing to server.log
2016-02-04 [10:59:24] system> Selected English (eng) as the base language
2016-02-04 [10:59:24] system> Starting Minecraft: PE server version v0.13.2 alpha
2016-02-04 [10:59:24] system> Opening server on 0.0.0.0:19132
2016-02-04 [10:59:24] system> This server is running ImagicalMine version 1.0dev "ImagicalMine" (API 1.14.0)
2016-02-04 [10:59:24] system> ImagicalMine is distributed under the LGPL License
2016-02-04 [10:59:24] system> Loading ClearLagg v1.1.0
2016-02-04 [10:59:24] system> Preparing level "world"
2016-02-04 [10:59:24] system> Enabling ClearLagg v1.1.0
2016-02-04 [10:59:24] system> Default game type: Creative Mode
2016-02-04 [10:59:24] system> Done (0.26s)! For help, type "help" or "?"
2016-02-05 [00:03:24] system> Simen[/148.252.120.238:19132] logged in with entity id 17 at (world, 110.7589, 70.2883, 117.4686)
2016-02-05 [00:03:25] system> Simen joined the game
2016-02-05 [00:12:16] emergency> An unrecoverable error has occurred and the server has crashed. Creating a crash dump
2016-02-05 [00:12:16] emergency> Please upload the "/var/games/minecraft/servers/FrodosPocket/CrashDump_Fri_Feb_5-00.12.16-CST_2016.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
2016-02-05 [00:12:17] system> Disabling ClearLagg v1.1.0
2016-02-05 [00:12:17] system> Simen left the game
2016-02-05 [00:12:17] system> Simen[/148.252.120.238:19132] logged out due to Server closed
2016-02-05 [00:12:17] system> Unloading level "world"

And here is my crash-dump file: 
[CrashDump_Fri_Feb_5-00.12.16-CST_2016.log.zip](https://github.com/ImagicalMine/ImagicalMine/files/119518/CrashDump_Fri_Feb_5-00.12.16-CST_2016.log.zip)

**Comment by Driesboy** [comment] 2016-02-05 17:47
big error i cannot use im for this reason

**Comment by ecoron** [comment] 2016-02-05 20:25
is the same like #821 should be fixed with commit https://github.com/ImagicalMine/ImagicalMine/commit/4e1687593bbed61a4c7dd98dd65bc1d72eea5094

**Comment by robske110** [comment] 2016-02-05 22:30
Fixed, please close!

**Closed** 2016-02-05 22:32 UTC
Labels: Critical, Duplicated
