### ISSUE TITLE
Binary Unpack Error

### ISSUE THREAD

**Issue by Guillaume351** [ImagicalMine/ImagicalMine#231364] opened 2016-03-13 08:44 UTC
- [x] This issue isn't related to any plugins or plugin related crashes.
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.

--------------------

Hello,
When I start my server, I get this error : 

> Warning: unpack(): Type N: not enough input, need 4, have 0 in phar:///root/Server/PocketMine-MP.phar/src/pocketmine/utils/Binary.php on line 335

It's impossible to join server. With an older ImagicalMine version, I did not have the error with the exact same plugins.

**Comment by remotevase** [comment] 2016-03-13 18:06
Go into pocketmine.yml and change the chunk load from 10 down to 5 or 2. This may help

**Comment by Guillaume351** [comment] 2016-04-16 19:05
Not fixed :/ Same issue as #231397

**Comment by deotern** [comment] 2016-04-17 12:04
//THIS IS NOT A IMAGICALMINE BUG
This is an UDP Flood or DDOS Attack, the hardest attack to stop... You're in the hot soup...
Because my server is suffering from this attack and I get exactly the same error...

Solution: mitigate or stop the attack... (P/S: Reinstalling Pocketmine, restarting, etc won't fix it)

INFO: I notice that many people reporting this issue recently, there's a man behind all these attacks, I have no idea who is this

EDIT: For more info, search Google for UDP Flood Attack

**Comment by Guillaume351** [comment] 2016-04-17 12:13
If it's an UDP flood attack, why only 1 or 2 of the 8 servers that I have on the same dedidacated server have the problem ?
It would at least explain why it's simultaneous.

**Comment by deotern** [comment] 2016-04-17 12:39
Yes, because UDP Flood Attack is target to one port only... unless that guy launch multiple attacks :(
True, if you notice, there're 2 points of this:
+ Only big server, well-known server having this error (Like Hippecraft, HappyParty, and if im not wrong, yours is cookie-build all those well known server)
+ This happening RANDOMLY, there's no a specified time when will this happen

I have do a check of my server, I fetch all data and I confirmed it's UDP Flood Attack, this attack is VERY VERY HARD to stop....

Answer of your questions:
1) Nope, because i checked the connection, it's extremely exceeded the normal count, that's why I confirmed it's an attack
2) I think no, because my server is DDOS Protected too... This is some kind of flood attack, I think it's different with normal DOS/DDOS Attack

**Comment by Guillaume351** [comment] 2016-04-17 12:40
Thank you for your time, I hope it will end soon :'(

**Comment by deotern** [comment] 2016-04-17 12:42
Nope, it won't... This issue started for my server since LAST WEEK... And it haven't stopped.... yes, it does stopped, but for a few hours only, then it started again....

That guy behind this is really going nut... Many servers are suffering from this already, you're not alone...

Btw, you're the cookie-build owner, right?

**Comment by remotevase** [comment] 2016-04-17 13:16
I think he is

**Comment by remotevase** [comment] 2016-04-17 13:16
Oops lol

**Closed by remotevase** 2016-04-17 13:16 UTC
Labels: Critical, Invalid, Irrelevant

**Comment by Guillaume351** [comment] 2016-04-17 13:23
Yep I am,  do you have a way to see all IPs connected/trying to connect to the server ? Maybe it's possible to isolate and reject suspicious IPs ... I can't migrate my servers, don't have time to transfer everything (database...)

**Comment by Guillaume351** [comment] 2016-04-17 13:44
Attack confirmed : changing the port makes the server works again. As the connection to port 19132 are randomly dispatched to an other port, it explains why not all servers have the issue. As most of my buildbattle servers are down, it means the attacks come from at least 5 - 6 different IPs

**Comment by deotern** [comment] 2016-04-17 14:06
Yep, I told you there's an attack already xD, but changing port is not a permanent solution. When he attacks another port, then the issue will arise again...

@Guillaume351 Do u have any idea to fix this?.... =_= except for changing port

The guy attacking our servers maybe is not alone, I mean maybe they have a team.. since they attack so many servers in one time.... Cookiebuild, Hippiecraft, my server and many more

**Comment by Guillaume351** [comment] 2016-04-17 14:08
Yep, but I can confirm it now :|

I'm not really good at linux/network stuff, so no solution for now... I will tell you here if there is any news :/ It's been more than 3 weeks that I have this bug

**Comment by Ragnok123** [comment] 2016-04-17 14:11
Check binaries

**Comment by deotern** [comment] 2016-04-17 14:14
@Guillaume351 wow... 3 weeks!?! and you don't go and check anything? LOL For me, it's 1 week


Really angry to those who attacking our server... Okay, we should keep update if there is any news :) I believe we can resolve this in one day :D

**Comment by Guillaume351** [comment] 2016-04-17 14:16
@deotern I had a lot of work, and I thought it was due to 0.14 - ImagicalMine bug. If anyone has a solution, help :+1:

**Comment by deotern** [comment] 2016-04-17 14:19
@Guillaume351 Same for me, because I used my own Pocketmine system called Pulse actaully... I thought there's bug in my code... LOL And just now, I found out it's a UDP Flood Attack.... :cry: 

Yeah, anybody have any idea to fix this? >...<

**Comment by Ragnok123** [comment] 2016-04-17 14:20
@deotern, just change ip/host.

**Comment by Ragnok123** [comment] 2016-04-17 14:21
I have sometimes 1x/month this problem, just changing ip or host

**Comment by Guillaume351** [comment] 2016-04-17 14:21
@Ragnok123 And if he DDoS my hostname IP (.cookie-build.com) ? Problem also is I have database and all servers in same location, I have to migrate everything

**Comment by deotern** [comment] 2016-04-17 14:22
@Ragnok123 I wouldn't work! As you redirect all connections from your hostname to your server IPv4 address using DNS... If u changed the IP, the redirected connections are still point to your new IP

**Comment by Ragnok123** [comment] 2016-04-17 14:42
Then ask host for better anti-ddos. Im using Stormwall and I have not problems with DDoS

**Comment by remotevase** [comment] 2016-04-17 20:24
Yes, but Stormwall u have to pay

**Comment by Guillaume351** [comment] 2016-04-19 14:16
First IP banned ! 
iptables -I INPUT -s 50.49.129.182 -j DROP

This IP was attacking one of my dedicated. Blocking it fixed the server.

Now trying to find for the second dedicated...

**Comment by Guillaume351** [comment] 2016-04-19 21:28
Update !

After a 'tcpdump -i eth0'

I saw that I was receiving a lot of UDP packets of size 7. I searched on the internet, and apparently a UDP packet must be 30..50+ of length at least to have usable data. So I did 


iptables -t raw -A PREROUTING -p udp -m length --length 7 -j DROP

It closes all packets with size 7.

Annnnnnd, seems to work ! 0 Build Battle down right now. Will update tomorrow to confirm this.

**Comment by remotevase** [comment] 2016-04-19 22:06
cool!

**Comment by deotern** [comment] 2016-04-20 08:12
@Guillaume351 Nice! :D Seems like a cure is avail!! Cheers! :fireworks:

**Comment by deotern** [comment] 2016-04-20 10:12
<//OFF TOPIC
@Guillaume351 
You run a server on a dedicated server, right?
Can you teach me how to run multiple Pocketmine Server in one dedicated server? :)

Also, I installed a fresh Pocketmine at my new 32GB RAM Dedi, but when I run, it gives me Segmentation Fault and it crashed... This happen only at my Dedicated server.... My VPS works fine...
Do you experience this Segmentation Fault too at your dedicated server before? Can you teach me how to solve this? Thank you :)

**Comment by deotern** [comment] 2016-04-20 11:16
@Guillaume351 
Based on my data receive from my VPS, I confirmed most of the attack is launched from kbronet, Taiwan.... When you google kbroent, you could found it's quite "famous" with spamming servers....

**Comment by Guillaume351** [comment] 2016-04-20 11:49
To dispatch 19132 connections to port 19132,19133,....19139 : 
iptables -t nat -A PREROUTING -p udp --dport 19132 -j REDIRECT --to-ports 19132-19139 --random

**Comment by deotern** [comment] 2016-04-20 11:53
Hmmm Thanks for that
@Guillaume351 
I have do this command:
`iptables -t raw -A PREROUTING -p udp -m length --length 7 -j DROP`
And this:
`sudo service iptables save`

But, it doesn't seem to block the UDP packets with length at 7... When I tcpdump, I still saw tons of UDP Packet with length 7 incoming...

**Comment by deotern** [comment] 2016-04-20 11:54
Do I need to restart my VPS or something?? Because when I did
`iptables -S`
I don't see the rules listed there...

**Comment by keithkfng** [comment] 2016-04-20 12:03
@deotern I don't think you saved the rules correctly. Don't you have to run a different command, 
Ike iptables-persistent save or something? And BTW, if you want to run multiple servers, use the "screen" command. Search it up on Google to find out more - very useful for running multiple servers at once on a dedicated server

**Comment by deotern** [comment] 2016-04-20 12:06
@keithkfng 
Hmmm I have no idea why, I have googled up and I think Im saving it correctly, I tried to add new rules, it's working....

Btw, I do know about screen command.... =_= It's a basic Linux command... 
My problem is Im having problem installing Pokcetmine on a dedicated server, always give me segmentation Fault Error, exactly same as this guy: https://github.com/PocketMine/PocketMine-MP/issues/4117

**Comment by Guillaume351** [comment] 2016-04-20 16:10
@deotern  What linux are you using ? I have no problem with CentOs

**Comment by Guillaume351** [comment] 2016-04-20 20:20
> Warning: unpack(): Type f: not enough input, need 4, have 3 in phar:///root/Server2/PocketMine-MP.phar/src/pocketmine/utils/Binary.php on line 358

Warning: unpack(): Type f: not enough input, need 4, have 0 in phar:///root/Server2/PocketMine-MP.phar/src/pocketmine/utils/Binary.php on line 358

Warning: unpack(): Type f: not enough input, need 4, have 0 in phar:///root/Server2/PocketMine-MP.phar/src/pocketmine/utils/Binary.php on line 358

Notice: Uninitialized string offset: 34 in phar:///root/Server2/PocketMine-MP.phar/src/pocketmine/utils/BinaryStream.php on line 172

Notice: Uninitialized string offset: 35 in phar:///root/Server2/PocketMine-MP.phar/src/pocketmine/utils/BinaryStream.php on line 172


The Empire strikes back ? New type of error : Type f.. 
Only had error once, rebooting seems to fix ? 
I will publish any update ...

**Comment by deotern** [comment] 2016-04-20 22:07
@Guillaume351
Im running on CentOS 7 :)
Can u try:

iptables -S

And check if the rules is actived? And can you do tcpdump again and see if u still receive UDP Packet Length 7?
Because check this out:
http://superuser.com/questions/362201/how-to-drop-traffic-before-it-hits-existing-iptables-conntrack-rule
We should use FORWARD CHAIN and the length need to be added with IP header..

**Comment by Guillaume351** [comment] 2016-04-21 13:51
They are still displayed, but as you can see on http://minecraftpocket-servers.com/server/9770/stats/, uptime fixed thanks to that

**Comment by deotern** [comment] 2016-04-22 02:36
@Guillaume351 
Can u teach me how to install Pocketmine on a dedicated server? LOL
I followed the exactly way to install Pocketmine as I did on my VPS, but it gives me segemntation fault..
Same as this: https://github.com/PocketMine/PocketMine-MP/issues/4117

There's some memory issue within my dedicated server, when u install Pocketmine on your dedicated server, do you change anything related with memory, partition thingy?

**Comment by Guillaume351** [comment] 2016-04-22 09:52
@deotern 

> mkdir Server;cd Server;yum update;yum install perl;yum install gcc;yum install make;yum install automake;yum install libtool;yum install autoconf;yum install m4;wget -q -O - http://get.pocketmine.net/ | bash -s - -v development -r

**Comment by Guillaume351** [comment] 2016-04-22 09:53
Replace bin with php7's bin
