### ISSUE TITLE
Planks from logs

### ISSUE THREAD

**Issue by Skyladd** [ImagicalMine/ImagicalMine#723] opened 2016-01-24 21:47 UTC
Planks still can't be made from logs. This was fixed in the latest build of ImagicalCORE.

**Comment by keithkfng** [comment] 2016-01-25 01:30
ImagicalCore shouldn't be used for production or use.

**Comment by Skyladd** [comment] 2016-01-25 03:30
ImagicalCore is the only version that allows players to craft planks on my server though. No one can craft wood to planks it only crafts into pressure plates.

**Comment by rWardy** [comment] 2016-01-25 12:14
I think this is same as #673 It only affects Android from what we can tell, but struggling to find correct fix.  Still being investigated.

**Comment by PocketKiller** [comment] 2016-01-25 20:25
oops, i thought ImagicalCorp

**Comment by kiyoshi-kurosaki** [comment] 2016-01-27 01:07
Fix 5a83a5d94b3a933f03ef36c6fbc4ca97c3a732ff

**Comment by rWardy** [comment] 2016-01-27 01:13
This is duplicate of #673 Above referenced fix will not correct this issue.

**Comment by kiyoshi-kurosaki** [comment] 2016-01-27 01:15
Aaahh i'm overheating xD

**Comment by rWardy** [comment] 2016-01-27 01:15
:)

**Closed** 2016-01-27 01:17 UTC
Labels: Duplicated
